// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWebASP.NET.Data;

namespace TestWebASP.NET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220303114309_tester")]
    partial class tester
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CharacterMovie", b =>
                {
                    b.Property<int>("CharactersId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("CharactersId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("CharacterMovie");

                    b.HasData(
                        new
                        {
                            CharactersId = 1,
                            MoviesId = 1
                        },
                        new
                        {
                            CharactersId = 2,
                            MoviesId = 2
                        },
                        new
                        {
                            CharactersId = 2,
                            MoviesId = 3
                        });
                });

            modelBuilder.Entity("TestWebASP.NET.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "Baba Yaga",
                            FullName = "John Wick",
                            Gender = "Male",
                            Picture = "https://en.wikipedia.org/wiki/John_Wick_(character)#/media/File:John_Wick_Keanu.jpeg"
                        },
                        new
                        {
                            Id = 2,
                            Alias = "Iron Man",
                            FullName = "Tony Stark",
                            Gender = "Male",
                            Picture = "https://ironman.fandom.com/wiki/Marvel%27s_Iron_Man?file=P170620_v_v8_ba.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Alias = "Spiderman",
                            FullName = "Peter Parker",
                            Gender = "Male",
                            Picture = "https://ironman.fandom.com/wiki/Marvel_Studios:_Iron_Man_2?file=P3546118_v_v8_af.jpg"
                        });
                });

            modelBuilder.Entity("TestWebASP.NET.Models.Franchise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Franchises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Scary movie",
                            Name = "Scare the **** out of you-Movies"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Superheros fighting to save the world",
                            Name = "Marvel"
                        });
                });

            modelBuilder.Entity("TestWebASP.NET.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Director")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MovieTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Trailer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Chad Stahelski",
                            FranchiseId = 1,
                            Genre = "Action, Crime, Thriller",
                            MovieTitle = "John Wick",
                            Picture = "https://witcher.fandom.com/wiki/The_Witcher_(TV_series)?file=Netflix+poster+s1.jpg",
                            ReleaseYear = 2014,
                            Trailer = "https://www.youtube.com/watch?v=2AUmvWm5ZDQ&ab_channel=LionsgateMovies"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Jon Favreau",
                            FranchiseId = 2,
                            Genre = "Action, Adventure, Sci-Fi",
                            MovieTitle = "Iron Man",
                            Picture = "https://upload.wikimedia.org/wikipedia/en/0/02/Iron_Man_%282008_film%29_poster.jpg",
                            ReleaseYear = 2008,
                            Trailer = "https://www.youtube.com/watch?v=8hYlB38asDY&ab_channel=TheMovieChanneI"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Jon Favreau",
                            FranchiseId = 2,
                            Genre = "Action, Adventure, Sci-Fi",
                            MovieTitle = "Iron Man 2",
                            Picture = "https://en.wikipedia.org/wiki/Iron_Man_2#/media/File:Iron_Man_2_poster.jpg",
                            ReleaseYear = 2010,
                            Trailer = "https://www.youtube.com/watch?v=BoohRoVA9WQ&ab_channel=Movieclips"
                        });
                });

            modelBuilder.Entity("CharacterMovie", b =>
                {
                    b.HasOne("TestWebASP.NET.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestWebASP.NET.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestWebASP.NET.Models.Movie", b =>
                {
                    b.HasOne("TestWebASP.NET.Models.Franchise", "Franchise")
                        .WithMany("Movies")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("TestWebASP.NET.Models.Franchise", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
